kafka:
  wages-topic:
    name: "wages-local"
    bootstrap-address: "localhost:9092"
    partitions: 1
    replication-factor: 1
    group-id: "wages-consumer-local"

spring:
  liquibase:
    enabled: true
    user: admin
    password: admin
  datasource:
    url: "jdbc:mysql://localhost:3306/db"
    username: consumer_app
    password: password

wage.tax:
  income-tax-percent: 20
