kafka:
  wages-topic:
    name: "wages-local"
    bootstrap-address: "localhost:29092,localhost:39092"
    partitions: 2
    replication-factor: 2
    group-id: "wages-consumer-local"

spring:
  liquibase:
    enabled: true
    user: root
    password: root
    parameters:
      consumer.app.user: ${spring.datasource.username}
      consumer.app.password: ${spring.datasource.password}
  datasource:
    url: "jdbc:mysql://localhost:3306/db"
    username: consumer_app
    password: password

wage.tax:
  income-tax-percent: 20
