server.port: 8070

kafka:
  wages-topic:
    name: "wages-local"
    bootstrap-address: "localhost:9092"
    partitions: 1
    replication-factor: 1
    group-id: "wages-consumer-local"

spring:
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.xml"
    user: admin
    password: admin
  datasource:
    url: "jdbc:mysql://localhost:3306/db"
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

wage.tax:
  income-tax-percent: 20
